version: '3.9'

services:
  prometheus:
    container_name: prometheus
    init: true
    image: prom/prometheus:latest
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - prom-data:/prometheus  
    ports:
      - 9090:9090
           
  pure-exporter:
    depends_on:
     - prometheus
    container_name: pure-exporter
    init: true
    image: quay.io/purestorage/pure-exporter:1.2.5-a
    restart: always
    ports:
     - 9491:9491

  grafana:
    depends_on:
     - prometheus
    container_name: grafana
    image: grafana/grafana
    volumes:
     - grafana-data:/var/lib/grafana
    ports:
     - 3000:3000

volumes:
  prom-data:
  grafana-data:
