# Flasharray sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'Flasharray'

# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

        #  - job_name: 'prometheus-node-exporter'
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    #  static_configs:
    #  - targets: ['localhost:9100']

  - job_name: 'pure_flasharray'
    scrape_interval: 10s
    metrics_path: /metrics/flasharray
    relabel_configs:
    # meta label of target address --> get parameter "pure_host"
      - source_labels: [__address__]
        target_label: __param_endpoint
    # label of target api token --> get parameter "pure_apitoken"
      - source_labels: [__pure_apitoken]
        target_label: __param_apitoken
    # display the pure host as the instance label
      - source_labels: [__address__]
        target_label: instance
    # point the exporter to the scraping endpoint of the exporter
      - target_label: __address__
        replacement: pure-exporter:9491 # address of the exporter, in debug mode
       # THIS NEEDS TO BE CHANGED TO YOUR ENVIRONMENT
        # Actual pure hosts (without a prometheus endpoint) as targets
    static_configs:
      - targets: [ 192.168.0.137 ]
        labels:
          __pure_apitoken: 57de518d-1a09-ebec-fec6-be953675c372

